# Generated by Django 3.2.14 on 2023-03-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('NonVegdiet', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=255)),
                ('Price', models.FloatField()),
                ('is_avilable', models.BooleanField(default=True)),
                ('quantity', models.CharField(max_length=255)),
            ],
        ),
    ]
